// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIe8divAjcxlI9CTkyZWfErckYPb-_34',
    appId: '1:944336719638:web:ef5b1a9091ac0a5a368a37',
    messagingSenderId: '944336719638',
    projectId: 'movie-app-ddbd9',
    authDomain: 'movie-app-ddbd9.firebaseapp.com',
    storageBucket: 'movie-app-ddbd9.firebasestorage.app',
    measurementId: 'G-T1GKLHXCH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Q3raBTPgYCHSlrDz5WNO39ZEH2feV0s',
    appId: '1:944336719638:android:b97b76f100d712bb368a37',
    messagingSenderId: '944336719638',
    projectId: 'movie-app-ddbd9',
    storageBucket: 'movie-app-ddbd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnYCRSxdoLJClP-PA5dedrrXhpR4yJ68',
    appId: '1:944336719638:ios:115e2bdafbe60109368a37',
    messagingSenderId: '944336719638',
    projectId: 'movie-app-ddbd9',
    storageBucket: 'movie-app-ddbd9.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIe8divAjcxlI9CTkyZWfErckYPb-_34',
    appId: '1:944336719638:web:e484ff04c15130e8368a37',
    messagingSenderId: '944336719638',
    projectId: 'movie-app-ddbd9',
    authDomain: 'movie-app-ddbd9.firebaseapp.com',
    storageBucket: 'movie-app-ddbd9.firebasestorage.app',
    measurementId: 'G-DHRDMBSFJT',
  );

}